<template>
    <div class="circle">
        <ul class="circle-container">
            <contentDot
            img="/ph-rund.png"
            alt=""
            title="title"
            desc="desc"/>
            <contentDot
            img="/ph-rund.png"
            alt=""
            title="title"
            desc="desc"/>
            <contentDot
            img="/ph-rund.png"
            alt=""
            title="title"
            desc="desc"/>
            <contentDot
            img="/ph-rund.png"
            alt=""
            title="title"
            desc="desc"/>
            <contentDot
            img="/ph-rund.png"
            alt=""
            title="title"
            desc="desc"/>
        </ul>
    </div>
</template>