<template>
    <div class="grid3">
        <cardDot
        img="/ph-rund.png"
        alt=""
        title="title"
        desc="desc"
        bg="mint"/>
        <cardDot
        img="/ph-rund.png"
        alt=""
        title="title"
        desc="desc"
        bg="rose"/>
        <cardDot
        img="/ph-rund.png"
        alt=""
        title="title"
        desc="desc"
        bg="babyblue"/>
    </div>
</template>